name: git_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  logging: ^1.2.0
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  redux: ^5.0.0
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
